import User, { roles } from '../models/User.js';
import AppError from '../utils/AppError.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { applyOwnership, ensureScope, scopedFilter } from '../middleware/scope.js';
import { audit } from '../utils/audit.js';
import { listResponse, pagination } from '../utils/query.js';

export const listUsers = asyncHandler(async (req, res) => { const { page, limit, skip } = pagination(req.query); const filter = scopedFilter(req); if (req.query.role) filter.role = req.query.role; if (req.query.search) filter.$or = ['name', 'email', 'phone'].map((x) => ({ [x]: { $regex: req.query.search, $options: 'i' } })); const [data, total] = await Promise.all([User.find(filter).select('-password').populate('organization branch').skip(skip).limit(limit).sort('-createdAt'), User.countDocuments(filter)]); listResponse(res, data, total, page, limit); });
export const createUser = asyncHandler(async (req, res) => { const body = applyOwnership(req, req.body); if (!roles.includes(body.role)) throw new AppError('Invalid user role'); if (body.role === 'SUPER_ADMIN' && req.user.role !== 'SUPER_ADMIN') throw new AppError('Only Super Admin may create Super Admin accounts', 403); if (req.user.role !== 'SUPER_ADMIN' && body.role !== 'DRIVER' && body.role !== 'FINANCE_OFFICER') throw new AppError('Only Super Admin may create management accounts', 403); const user = await User.create(body); await audit(req, 'CREATE', 'User', user._id, `Created ${user.role} user`); res.status(201).json({ success: true, message: 'User created', data: user }); });
export const updateUser = asyncHandler(async (req, res) => { const user = await User.findById(req.params.id); if (!user) throw new AppError('User not found', 404); ensureScope(req, user); const body = { ...req.body }; delete body.password; delete body.organization; delete body.branch; if (body.role && req.user.role !== 'SUPER_ADMIN') throw new AppError('Only Super Admin may change roles', 403); Object.assign(user, body); await user.save(); await audit(req, 'UPDATE', 'User', user._id, 'Updated user'); res.json({ success: true, message: 'User updated', data: user }); });
export const deleteUser = asyncHandler(async (req, res) => { const user = await User.findById(req.params.id); if (!user) throw new AppError('User not found', 404); ensureScope(req, user); user.isActive = false; await user.save(); await audit(req, 'DEACTIVATE', 'User', user._id, 'Deactivated user'); res.json({ success: true, message: 'User deactivated' }); });
export const profile = asyncHandler(async (req, res) => res.json({ success: true, data: req.user }));
