import { Router } from 'express';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import assignmentRoutes from './assignmentRoutes.js';
import tripRoutes from './tripRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import { makeCrudRoutes, financeRoles, staffRoles } from './crudRoutes.js';
import { organizations, branches, vehicles, drivers, routes, fuel, maintenance, incidents, documents, expenses, auditLogs } from '../controllers/resources.js';
import { allow, protect } from '../middleware/auth.js';
import { upload } from '../middleware/upload.js';
import Incident from '../models/Incident.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { ensureScope } from '../middleware/scope.js';
import AppError from '../utils/AppError.js';
import { audit } from '../utils/audit.js';

const router = Router();
router.use('/auth', authRoutes); router.use('/users', userRoutes);
router.use('/organizations', makeCrudRoutes(organizations, ['SUPER_ADMIN']));
router.use('/branches', makeCrudRoutes(branches, ['SUPER_ADMIN']));
router.use('/vehicles', makeCrudRoutes(vehicles, staffRoles, 'image'));
router.use('/drivers', makeCrudRoutes(drivers, staffRoles));
router.use('/routes', makeCrudRoutes(routes, staffRoles));
router.use('/assignments', assignmentRoutes); router.use('/trips', tripRoutes);
router.use('/fuel', makeCrudRoutes(fuel, [...financeRoles, 'DRIVER'], 'receiptImage'));
router.use('/maintenance', makeCrudRoutes(maintenance, staffRoles, 'invoice'));
const incidentRouter = makeCrudRoutes(incidents, [...staffRoles, 'DRIVER'], 'evidence', true);
incidentRouter.patch('/:id/status', protect, allow(...staffRoles), asyncHandler(async (req, res) => { const incident = await Incident.findById(req.params.id); if (!incident) throw new AppError('Incident not found', 404); ensureScope(req, incident); incident.status = req.body.status; if (['RESOLVED', 'CLOSED'].includes(incident.status)) incident.resolvedAt = new Date(); await incident.save(); await audit(req, 'STATUS_CHANGE', 'Incident', incident._id, `Incident status changed to ${incident.status}`); res.json({ success: true, data: incident }); }));
router.use('/incidents', incidentRouter);
router.use('/documents', makeCrudRoutes(documents, staffRoles, 'fileUrl'));
router.use('/expenses', makeCrudRoutes(expenses, [...financeRoles, 'DRIVER'], 'receipt'));
router.use('/audit-logs', makeCrudRoutes(auditLogs, ['SUPER_ADMIN']));
router.use('/notifications', notificationRoutes); router.use('/dashboard', dashboardRoutes);
export default router;
