import 'dotenv/config';
import { connectDatabase } from '../config/db.js';
import Organization from '../models/Organization.js'; import Branch from '../models/Branch.js'; import User from '../models/User.js'; import Driver from '../models/Driver.js'; import Vehicle from '../models/Vehicle.js'; import Route from '../models/Route.js'; import Assignment from '../models/Assignment.js'; import Trip from '../models/Trip.js'; import FuelEntry from '../models/FuelEntry.js'; import Maintenance from '../models/Maintenance.js'; import Incident from '../models/Incident.js'; import Expense from '../models/Expense.js'; import Document from '../models/Document.js';

const password = process.env.SEED_PASSWORD || 'FleetSphere@123';
const email = (name) => `${name.toLowerCase().replace(/\s/g, '.')}@fleetsphere.test`;
async function seed() {
  await connectDatabase();
  await Promise.all([Organization.deleteMany(), Branch.deleteMany(), User.deleteMany(), Driver.deleteMany(), Vehicle.deleteMany(), Assignment.deleteMany(), Route.deleteMany(), Trip.deleteMany(), FuelEntry.deleteMany(), Maintenance.deleteMany(), Incident.deleteMany(), Expense.deleteMany(), Document.deleteMany()]);
  const org = await Organization.create({ name: 'FleetSphere Logistics', email: 'ops@fleetsphere.test', phone: '+91 98765 43210', address: '12 Logistics Park, Hyderabad' });
  const [hyd, blr] = await Branch.create([{ name: 'Hyderabad Hub', organization: org._id, address: 'Madhapur', city: 'Hyderabad', state: 'Telangana', pincode: '500081' }, { name: 'Bengaluru Hub', organization: org._id, address: 'Whitefield', city: 'Bengaluru', state: 'Karnataka', pincode: '560066' }]);
  const users = await User.create([
    { name: 'Aarav Admin', email: email('Aarav Admin'), password, role: 'SUPER_ADMIN', organization: org._id },
    { name: 'Meera Fleet', email: email('Meera Fleet'), password, role: 'FLEET_MANAGER', organization: org._id },
    { name: 'Ishaan Hyderabad', email: email('Ishaan Hyderabad'), password, role: 'BRANCH_MANAGER', organization: org._id, branch: hyd._id },
    { name: 'Kavya Bengaluru', email: email('Kavya Bengaluru'), password, role: 'BRANCH_MANAGER', organization: org._id, branch: blr._id },
    { name: 'Farah Finance', email: email('Farah Finance'), password, role: 'FINANCE_OFFICER', organization: org._id }
  ]);
  const driverUsers = await User.create(['Ravi Kumar', 'Ananya Rao', 'Sanjay Patel', 'Divya Singh', 'Arjun Reddy'].map((name, i) => ({ name, email: email(name), password, role: 'DRIVER', organization: org._id, branch: i < 3 ? hyd._id : blr._id })));
  await Branch.findByIdAndUpdate(hyd, { manager: users[2]._id }); await Branch.findByIdAndUpdate(blr, { manager: users[3]._id });
  const drivers = await Driver.create(driverUsers.map((user, i) => ({ user: user._id, licenseNumber: `TS${100000 + i}`, licenseExpiry: new Date('2029-12-31'), joiningDate: new Date('2023-01-01'), emergencyContact: '+91 90000 00000', status: 'AVAILABLE', organization: org._id, branch: i < 3 ? hyd._id : blr._id })));
  const vehicles = await Vehicle.create(Array.from({ length: 10 }, (_, i) => ({ registrationNumber: `TS09FS${1200 + i}`, vehicleType: i < 6 ? 'Truck' : 'Van', make: i % 2 ? 'Tata' : 'Ashok Leyland', model: i % 2 ? 'Prima' : 'Dost', year: 2021 + (i % 4), fuelType: 'DIESEL', capacity: i < 6 ? 12000 : 2500, odometer: 18000 + (i * 1400), status: 'AVAILABLE', organization: org._id, branch: i < 6 ? hyd._id : blr._id })));
  for (let i = 0; i < drivers.length; i += 1) { const assignment = await Assignment.create({ vehicle: vehicles[i]._id, driver: drivers[i]._id, organization: org._id, branch: drivers[i].branch, assignedBy: users[1]._id }); await Vehicle.findByIdAndUpdate(vehicles[i], { assignedDriver: drivers[i]._id, status: 'ASSIGNED' }); await Driver.findByIdAndUpdate(drivers[i], { assignedVehicle: vehicles[i]._id, status: 'ASSIGNED' }); void assignment; }
  const routes = await Route.create([{ name: 'Hyderabad to Vijayawada', source: 'Hyderabad', destination: 'Vijayawada', distance: 275, estimatedDuration: 360, stops: ['Suryapet'], organization: org._id, branch: hyd._id }, { name: 'Hyderabad City Run', source: 'Madhapur', destination: 'Uppal', distance: 35, estimatedDuration: 90, organization: org._id, branch: hyd._id }, { name: 'Bengaluru to Mysuru', source: 'Bengaluru', destination: 'Mysuru', distance: 145, estimatedDuration: 210, organization: org._id, branch: blr._id }]);
  const now = new Date(); const day = 24 * 60 * 60 * 1000;
  const trips = await Trip.create([{ tripNumber: 'TRP-1001', vehicle: vehicles[0]._id, driver: drivers[0]._id, route: routes[0]._id, source: 'Hyderabad', destination: 'Vijayawada', scheduledStart: new Date(now - 4 * day), scheduledEnd: new Date(now - 3.8 * day), actualStart: new Date(now - 4 * day), actualEnd: new Date(now - 3.8 * day), startOdometer: 18000, endOdometer: 18275, distance: 275, status: 'COMPLETED', statusHistory: [{ status: 'COMPLETED', changedBy: users[1]._id }], organization: org._id, branch: hyd._id, createdBy: users[1]._id }, { tripNumber: 'TRP-1002', vehicle: vehicles[3]._id, driver: drivers[3]._id, route: routes[2]._id, source: 'Bengaluru', destination: 'Mysuru', scheduledStart: new Date(now.getTime() + day), scheduledEnd: new Date(now.getTime() + 1.2 * day), status: 'ASSIGNED', statusHistory: [{ status: 'ASSIGNED', changedBy: users[1]._id }], organization: org._id, branch: blr._id, createdBy: users[1]._id }]);
  await FuelEntry.create([{ vehicle: vehicles[0]._id, driver: drivers[0]._id, date: new Date(now - 4 * day), odometer: 18000, liters: 42, pricePerLiter: 96, fuelStation: 'HP Suryapet', organization: org._id, branch: hyd._id, createdBy: driverUsers[0]._id }, { vehicle: vehicles[3]._id, driver: drivers[3]._id, liters: 35, pricePerLiter: 97, odometer: 22000, fuelStation: 'Indian Oil Bengaluru', organization: org._id, branch: blr._id, createdBy: driverUsers[3]._id }]);
  await Maintenance.create([{ vehicle: vehicles[7]._id, maintenanceType: 'SERVICE', serviceDate: new Date(now.getTime() + 7 * day), nextServiceDate: new Date(now.getTime() + 180 * day), currentOdometer: 27800, partsCost: 2500, laborCost: 1500, status: 'SCHEDULED', organization: org._id, branch: blr._id, createdBy: users[1]._id }, { vehicle: vehicles[2]._id, maintenanceType: 'TYRE', serviceDate: new Date(now - 2 * day), partsCost: 18000, laborCost: 2000, status: 'COMPLETED', organization: org._id, branch: hyd._id, createdBy: users[1]._id }]);
  await Incident.create({ incidentNumber: 'INC-1001', vehicle: vehicles[1]._id, driver: drivers[1]._id, date: new Date(now - day), location: 'Outer Ring Road, Hyderabad', title: 'Minor side mirror damage', description: 'Vehicle sustained minor damage while parked.', severity: 'LOW', status: 'REPORTED', organization: org._id, branch: hyd._id, reportedBy: driverUsers[1]._id });
  await Expense.create([{ category: 'TOLL', amount: 680, date: new Date(now - 4 * day), vehicle: vehicles[0]._id, driver: drivers[0]._id, trip: trips[0]._id, description: 'Highway tolls', organization: org._id, branch: hyd._id, createdBy: driverUsers[0]._id }, { category: 'REPAIR', amount: 1500, vehicle: vehicles[1]._id, description: 'Mirror replacement', organization: org._id, branch: hyd._id, createdBy: users[1]._id }]);
  await Document.create({ title: 'TS09FS1200 Insurance', type: 'INSURANCE', fileUrl: '/uploads/sample-insurance.pdf', fileName: 'sample-insurance.pdf', expiryDate: new Date('2027-04-30'), vehicle: vehicles[0]._id, organization: org._id, branch: hyd._id, uploadedBy: users[1]._id });
  console.log(`Seeded FleetSphere. Password for all accounts: ${password}`); console.log(`Admin: ${email('Aarav Admin')}`); await process.exit(0);
}
seed().catch((err) => { console.error(err); process.exit(1); });
