import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';
const common = [{ to: '/dashboard', icon: '▦', label: 'Dashboard' }, { to: '/notifications', icon: '◉', label: 'Notifications' }, { to: '/profile', icon: '◌', label: 'Profile' }];
const menu = {
  SUPER_ADMIN: [{ to: '/super-admin/organizations', icon: '◈', label: 'Organizations' }, { to: '/super-admin/branches', icon: '⌘', label: 'Branches' }, { to: '/super-admin/users', icon: '♙', label: 'Users' }, { to: '/super-admin/audit-logs', icon: '◫', label: 'Audit logs' }, { to: '/fleet/vehicles', icon: '▣', label: 'Vehicles' }, { to: '/fleet/drivers', icon: '♧', label: 'Drivers' }, { to: '/fleet/trips', icon: '↝', label: 'Trips' }],
  FLEET_MANAGER: [{ to: '/fleet/vehicles', icon: '▣', label: 'Vehicles' }, { to: '/fleet/drivers', icon: '♧', label: 'Drivers' }, { to: '/fleet/assignments', icon: '⇄', label: 'Assignments' }, { to: '/fleet/routes', icon: '⌁', label: 'Routes' }, { to: '/fleet/trips', icon: '↝', label: 'Trips' }, { to: '/fleet/maintenance', icon: '⚙', label: 'Maintenance' }, { to: '/fleet/incidents', icon: '⚠', label: 'Incidents' }, { to: '/fleet/documents', icon: '▤', label: 'Documents' }, { to: '/fleet/expenses', icon: '₹', label: 'Expenses' }],
  BRANCH_MANAGER: [{ to: '/fleet/vehicles', icon: '▣', label: 'Vehicles' }, { to: '/fleet/drivers', icon: '♧', label: 'Drivers' }, { to: '/fleet/trips', icon: '↝', label: 'Trips' }, { to: '/fleet/maintenance', icon: '⚙', label: 'Maintenance' }, { to: '/fleet/incidents', icon: '⚠', label: 'Incidents' }, { to: '/fleet/expenses', icon: '₹', label: 'Expenses' }],
  DRIVER: [{ to: '/driver/trips', icon: '↝', label: 'My trips' }, { to: '/driver/fuel', icon: '⛽', label: 'Fuel entries' }, { to: '/driver/incidents', icon: '⚠', label: 'Report incident' }, { to: '/driver/expenses', icon: '₹', label: 'My expenses' }],
  FINANCE_OFFICER: [{ to: '/finance/fuel', icon: '⛽', label: 'Fuel records' }, { to: '/finance/maintenance', icon: '⚙', label: 'Maintenance costs' }, { to: '/finance/expenses', icon: '₹', label: 'Expenses' }, { to: '/finance/reports', icon: '▥', label: 'Cost analytics' }]
};
export default function AppLayout() { const { user, logout } = useAuthStore(); const navigate = useNavigate(); const links = [...(menu[user.role] || []), ...common]; return <div className="shell"><aside className="sidebar"><NavLink className="brand" to="/dashboard"><span>F</span> FleetSphere</NavLink><div className="workspace">WORKSPACE</div><nav>{links.map((link) => <NavLink key={link.to} to={link.to} className="nav-link"><i>{link.icon}</i>{link.label}</NavLink>)}</nav><div className="sidebar-user"><div className="avatar">{user.name?.[0]}</div><div><strong>{user.name}</strong><small>{user.role.replace('_', ' ')}</small></div><button aria-label="Sign out" onClick={async () => { await logout(); navigate('/login'); }}>↪</button></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">{user.organization?.name || 'FleetSphere Logistics'}</span><h1>Operations command center</h1></div><NavLink to="/notifications" className="bell">◉</NavLink></header><Outlet /></main></div>; }
