import { useEffect } from 'react'; import { Navigate, Route, Routes } from 'react-router-dom'; import { useAuthStore } from './store/authStore'; import ProtectedRoute from './routes/ProtectedRoute'; import AppLayout from './layouts/AppLayout'; import AuthPage from './pages/AuthPage'; import DashboardPage from './pages/DashboardPage'; import ProfilePage from './pages/ProfilePage'; import NotificationsPage from './pages/NotificationsPage'; import ResourcePage from './pages/ResourcePage'; import AssignmentsPage from './pages/AssignmentsPage';
const allStaff = ['SUPER_ADMIN', 'FLEET_MANAGER', 'BRANCH_MANAGER']; const finance = [...allStaff, 'FINANCE_OFFICER']; const driverFinancial = [...finance, 'DRIVER'];
const configs = {
  organizations: { title: 'Organizations', path: '/organizations', fields: [{ name: 'name', label: 'Organization', required: true }, { name: 'email', label: 'Email', required: true, input: 'email' }, { name: 'phone', label: 'Phone' }, { name: 'address', label: 'Address' }, { name: 'isActive', label: 'Active', options: ['true', 'false'] }] },
  branches: { title: 'Branches', path: '/branches', fields: [{ name: 'name', label: 'Branch', required: true }, { name: 'city', label: 'City' }, { name: 'state', label: 'State' }, { name: 'pincode', label: 'Pincode' }, { name: 'organization', label: 'Organization ID', required: true }, { name: 'isActive', label: 'Status', status: true, options: ['true', 'false'] }] },
  users: { title: 'Users', path: '/users', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Email', required: true, input: 'email' }, { name: 'role', label: 'Role', required: true, status: true, options: ['SUPER_ADMIN', 'FLEET_MANAGER', 'BRANCH_MANAGER', 'DRIVER', 'FINANCE_OFFICER'] }, { name: 'phone', label: 'Phone' }, { name: 'branch', label: 'Branch ID' }, { name: 'isActive', label: 'Active', options: ['true', 'false'] }, { name: 'password', label: 'Password', input: 'password' }] },
  audit: { title: 'Audit logs', path: '/audit-logs', canCreate: false, fields: [{ name: 'action', label: 'Action', status: true }, { name: 'entity', label: 'Entity' }, { name: 'description', label: 'Description' }, { name: 'user', label: 'User' }, { name: 'createdAt', label: 'Created', type: 'date' }] },
  vehicles: { title: 'Vehicles', path: '/vehicles', fields: [{ name: 'registrationNumber', label: 'Registration number', required: true }, { name: 'vehicleType', label: 'Vehicle type', required: true }, { name: 'make', label: 'Make' }, { name: 'model', label: 'Model' }, { name: 'status', label: 'Status', status: true, options: ['AVAILABLE', 'ASSIGNED', 'ON_TRIP', 'MAINTENANCE', 'INACTIVE'] }, { name: 'odometer', label: 'Odometer', type: 'number' }, { name: 'capacity', label: 'Capacity', type: 'number' }, { name: 'branch', label: 'Branch ID', required: true }, { name: 'image', label: 'Vehicle image', input: 'file' }] },
  drivers: { title: 'Drivers', path: '/drivers', fields: [{ name: 'licenseNumber', label: 'License number', required: true }, { name: 'user', label: 'User ID', required: true }, { name: 'licenseExpiry', label: 'License expiry', required: true, type: 'date' }, { name: 'status', label: 'Status', status: true, options: ['AVAILABLE', 'ASSIGNED', 'ON_TRIP', 'ON_LEAVE', 'INACTIVE'] }, { name: 'emergencyContact', label: 'Emergency contact' }, { name: 'branch', label: 'Branch ID', required: true }] },
  routes: { title: 'Routes', path: '/routes', fields: [{ name: 'name', label: 'Route name', required: true }, { name: 'source', label: 'Source', required: true }, { name: 'destination', label: 'Destination', required: true }, { name: 'distance', label: 'Distance (km)', required: true, type: 'number' }, { name: 'estimatedDuration', label: 'Duration (min)', type: 'number' }, { name: 'branch', label: 'Branch ID', required: true }] },
  trips: { title: 'Trips', path: '/trips', fields: [{ name: 'tripNumber', label: 'Trip number', required: true }, { name: 'vehicle', label: 'Vehicle ID', required: true }, { name: 'driver', label: 'Driver ID', required: true }, { name: 'source', label: 'Source' }, { name: 'destination', label: 'Destination' }, { name: 'status', label: 'Status', status: true, options: ['PLANNED', 'ASSIGNED', 'STARTED', 'DELAYED', 'COMPLETED', 'CANCELLED'] }, { name: 'scheduledStart', label: 'Start', type: 'date', required: true }, { name: 'scheduledEnd', label: 'End', type: 'date', required: true }, { name: 'branch', label: 'Branch ID', required: true }] },
  fuel: { title: 'Fuel records', path: '/fuel', fields: [{ name: 'vehicle', label: 'Vehicle ID', required: true }, { name: 'date', label: 'Date', type: 'date' }, { name: 'liters', label: 'Liters', required: true, type: 'number' }, { name: 'pricePerLiter', label: 'Price per liter', required: true, type: 'currency' }, { name: 'totalCost', label: 'Total cost', type: 'currency', editable: false }, { name: 'odometer', label: 'Odometer', required: true, type: 'number' }, { name: 'fuelStation', label: 'Fuel station' }, { name: 'receiptImage', label: 'Receipt', input: 'file' }] },
  maintenance: { title: 'Maintenance', path: '/maintenance', fields: [{ name: 'maintenanceType', label: 'Type', required: true, options: ['SERVICE', 'REPAIR', 'INSPECTION', 'TYRE', 'OIL_CHANGE', 'OTHER'] }, { name: 'vehicle', label: 'Vehicle ID', required: true }, { name: 'serviceDate', label: 'Service date', required: true, type: 'date' }, { name: 'status', label: 'Status', status: true, options: ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'CANCELLED'] }, { name: 'totalCost', label: 'Total cost', type: 'currency', editable: false }, { name: 'partsCost', label: 'Parts cost', type: 'currency' }, { name: 'laborCost', label: 'Labor cost', type: 'currency' }, { name: 'invoice', label: 'Invoice', input: 'file' }] },
  incidents: { title: 'Incidents', path: '/incidents', fields: [{ name: 'incidentNumber', label: 'Incident number', required: true }, { name: 'title', label: 'Title', required: true }, { name: 'severity', label: 'Severity', status: true, options: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] }, { name: 'status', label: 'Status', status: true, options: ['REPORTED', 'UNDER_INVESTIGATION', 'RESOLVED', 'CLOSED'] }, { name: 'vehicle', label: 'Vehicle ID', required: true }, { name: 'date', label: 'Date', type: 'date' }, { name: 'description', label: 'Description', required: true }, { name: 'evidence', label: 'Evidence', input: 'file' }] },
  documents: { title: 'Documents', path: '/documents', fields: [{ name: 'title', label: 'Title', required: true }, { name: 'type', label: 'Type', options: ['INSURANCE', 'REGISTRATION', 'LICENSE', 'PERMIT', 'INVOICE', 'OTHER'] }, { name: 'fileUrl', label: 'File', required: true, input: 'file' }, { name: 'expiryDate', label: 'Expiry date', type: 'date' }, { name: 'vehicle', label: 'Vehicle ID' }, { name: 'driver', label: 'Driver ID' }] },
  expenses: { title: 'Expenses', path: '/expenses', fields: [{ name: 'category', label: 'Category', required: true, options: ['FUEL', 'MAINTENANCE', 'TOLL', 'TRIP', 'REPAIR', 'OTHER'] }, { name: 'amount', label: 'Amount', required: true, type: 'currency' }, { name: 'date', label: 'Date', type: 'date' }, { name: 'description', label: 'Description' }, { name: 'vehicle', label: 'Vehicle ID' }, { name: 'trip', label: 'Trip ID' }, { name: 'receipt', label: 'Receipt', input: 'file' }] }
};
const Page = ({ config }) => <ResourcePage {...config} />;
export default function App() { const checkAuth = useAuthStore((s) => s.checkAuth); useEffect(() => { checkAuth(); }, [checkAuth]); return <Routes><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route element={<ProtectedRoute />}><Route element={<AppLayout />}><Route path="/dashboard" element={<DashboardPage />} /><Route path="/profile" element={<ProfilePage />} /><Route path="/notifications" element={<NotificationsPage />} /><Route element={<ProtectedRoute roles={['SUPER_ADMIN']} />}><Route path="/super-admin/organizations" element={<Page config={configs.organizations} />} /><Route path="/super-admin/branches" element={<Page config={configs.branches} />} /><Route path="/super-admin/users" element={<Page config={configs.users} />} /><Route path="/super-admin/audit-logs" element={<Page config={configs.audit} />} /></Route><Route element={<ProtectedRoute roles={allStaff} />}><Route path="/fleet/vehicles" element={<Page config={configs.vehicles} />} /><Route path="/fleet/drivers" element={<Page config={configs.drivers} />} /><Route path="/fleet/assignments" element={<AssignmentsPage />} /><Route path="/fleet/routes" element={<Page config={configs.routes} />} /><Route path="/fleet/trips" element={<Page config={configs.trips} />} /><Route path="/fleet/maintenance" element={<Page config={configs.maintenance} />} /><Route path="/fleet/incidents" element={<Page config={configs.incidents} />} /><Route path="/fleet/documents" element={<Page config={configs.documents} />} /><Route path="/fleet/expenses" element={<Page config={configs.expenses} />} /></Route><Route element={<ProtectedRoute roles={driverFinancial} />}><Route path="/driver/trips" element={<Page config={{ ...configs.trips, canCreate: false }} />} /><Route path="/driver/fuel" element={<Page config={configs.fuel} />} /><Route path="/driver/incidents" element={<Page config={configs.incidents} />} /><Route path="/driver/expenses" element={<Page config={configs.expenses} />} /></Route><Route element={<ProtectedRoute roles={finance} />}><Route path="/finance/fuel" element={<Page config={configs.fuel} />} /><Route path="/finance/maintenance" element={<Page config={{ ...configs.maintenance, canCreate: false }} />} /><Route path="/finance/expenses" element={<Page config={configs.expenses} />} /><Route path="/finance/reports" element={<DashboardPage />} /></Route></Route></Route><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes>; }
